---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-lynq-sh-v1-lynqform
  failurePolicy: Fail
  name: mlynqform.kb.io
  rules:
  - apiGroups:
    - operator.lynq.sh
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lynqforms
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-lynq-sh-v1-lynqhub
  failurePolicy: Fail
  name: mlynqhub.kb.io
  rules:
  - apiGroups:
    - operator.lynq.sh
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lynqhubs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-lynq-sh-v1-lynqform
  failurePolicy: Fail
  name: vlynqform.kb.io
  rules:
  - apiGroups:
    - operator.lynq.sh
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lynqforms
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-lynq-sh-v1-lynqhub
  failurePolicy: Fail
  name: vlynqhub.kb.io
  rules:
  - apiGroups:
    - operator.lynq.sh
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lynqhubs
  sideEffects: None
