{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lynq-operator.webhookServiceName" . }}
  namespace: {{ include "lynq-operator.namespace" . }}
  labels:
    {{- include "lynq-operator.labels" . | nindent 4 }}
  {{- with .Values.webhook.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhook.serviceType }}
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{ .Values.webhook.port }}
    name: webhook
  selector:
    {{- include "lynq-operator.selectorLabels" . | nindent 4 }}
{{- end }}
