{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "lynq-operator.validatingWebhookName" . }}
  labels:
    {{- include "lynq-operator.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "lynq-operator.namespace" . }}/{{ include "lynq-operator.webhookCertificateName" . }}
  {{- end }}
webhooks:
- name: vlynqhub.kb.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "lynq-operator.webhookServiceName" . }}
      namespace: {{ include "lynq-operator.namespace" . }}
      path: /validate-operator-lynq-sh-v1-lynqhub
  failurePolicy: Fail
  rules:
  - apiGroups:
    - operator.lynq.sh
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lynqhubs
  sideEffects: None
- name: vlynqform.kb.io
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "lynq-operator.webhookServiceName" . }}
      namespace: {{ include "lynq-operator.namespace" . }}
      path: /validate-operator-lynq-sh-v1-lynqform
  failurePolicy: Fail
  rules:
  - apiGroups:
    - operator.lynq.sh
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lynqforms
  sideEffects: None
{{- end }}
