# This rule is not used by the project lynq itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over operator.lynq.sh.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lynq
    app.kubernetes.io/managed-by: kustomize
  name: lynqhub-admin-role
rules:
- apiGroups:
  - operator.lynq.sh
  resources:
  - lynqhubs
  verbs:
  - '*'
- apiGroups:
  - operator.lynq.sh
  resources:
  - lynqhubs/status
  verbs:
  - get
